apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          imagem: kubedevio/web-page:blue
          ports:
            - containerPort: 80
